name: Build and Deploy Storybook

on: 
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: [self-hosted,linux]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        run: npm install
      - name: Deploy 
        run: npm run deploy-storybook